apiVersion: v2
name: ghost
description: A Helm chart for Ghost on Kubernetes

type: application

maintainers:
  - name: groundhog2k

version: 0.76.3

appVersion: "5.33.8"

dependencies:
  - name: mariadb
    version: 0.2.24
    repository: "https://groundhog2k.github.io/helm-charts"
    condition: mariadb.enabled
  - name: mysql
    version: 0.1.6
    repository: "https://groundhog2k.github.io/helm-charts"
    condition: mysql.enabled
