name: Manual release helm chart

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Add dependencies
        run: |
          helm repo add groundhog2k https://groundhog2k.github.io/helm-charts
      - name: Run Release
        uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
